name: vehiclerent
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.1
  firebase_core: ^2.4.0
  firebase_database: ^10.0.8
  cloud_firestore: ^4.1.0
  firebase_storage: ^11.0.9
  image_picker: ^1.0.5
  provider: ^6.0.1
  firebase_messaging: ^14.7.19
  flutter_map: ^3.1.0
  latlong2: ^0.8.1
  geolocator: ^9.0.2
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/